<?php

declare (strict_types=1);
/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @since         3.5.0
 * @license       https://www.opensource.org/licenses/mit-license.php MIT License
 */
namespace Cake\Http\Middleware;

use ArrayAccess;
use Cake\Core\Exception\Cake_Exception;
use Cake\Http\Cookie\Cookie;
use Cake\Http\Cookie\Cookie_Interface;
use Cake\Http\Exception\Invalid_Csrf_Token_Exception;
use Cake\Http\Response;
use function Cake\I18n\__d;
use Cake\Utility\Hash;
use Cake\Utility\Security;
use InvalidArgumentException;
use Psr\Http\Message\Response_Interface;
use Psr\Http\Message\Server_Request_Interface;
use Psr\Http\Server\Middleware_Interface;
use Psr\Http\Server\Request_Handler_Interface;
/**
 * Provides CSRF protection & validation.
 *
 * This middleware adds a CSRF token to a cookie. The cookie value is compared to
 * token in request data, or the X-CSRF-Token header on each PATCH, POST,
 * PUT, or DELETE request. This is known as "double submit cookie" technique.
 *
 * If the request data is missing or does not match the cookie data,
 * an InvalidCsrfTokenException will be raised.
 *
 * This middleware integrates with the FormHelper automatically and when
 * used together your forms will have CSRF tokens automatically added
 * when `$this->Form->create(...)` is used in a view.
 *
 * @see https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#double-submit-cookie
 */
class Csrf_Protection_Middleware implements Middleware_Interface
{
    /**
     * Config for the CSRF handling.
     *
     *  - `cookieName` The name of the cookie to send.
     *  - `expiry` A strtotime compatible value of how long the CSRF token should last.
     *    Defaults to browser session.
     *  - `secure` Whether the cookie will be set with the Secure flag. Defaults to false.
     *  - `httponly` Whether the cookie will be set with the HttpOnly flag. Defaults to false.
     *  - `samesite` "SameSite" attribute for cookies. Defaults to `null`.
     *    Valid values: `CookieInterface::SAMESITE_LAX`, `CookieInterface::SAMESITE_STRICT`,
     *    `CookieInterface::SAMESITE_NONE` or `null`.
     *  - `field` The form field to check. Changing this will also require configuring
     *    FormHelper.
     *
     * @var array<string, mixed>
     */
    protected array $_config = ['cookieName' => 'csrfToken', 'expiry' => 0, 'secure' => false, 'httponly' => false, 'samesite' => null, 'field' => '_csrfToken'];
    /**
     * Callback for deciding whether to skip the token check for particular request.
     *
     * CSRF protection token check will be skipped if the callback returns `true`.
     *
     * @var callable|null
     */
    protected $skip_check_callback;
    /**
     * @var int
     */
    public const TOKEN_VALUE_LENGTH = 16;
    /**
     * Tokens have an hmac generated so we can ensure
     * that tokens were generated by our application.
     *
     * Should be TOKEN_VALUE_LENGTH + strlen(hmac)
     *
     * We are currently using sha1 for the hmac which
     * creates 40 bytes.
     *
     * @var int
     */
    public const TOKEN_WITH_CHECKSUM_LENGTH = 56;
    /**
     * Constructor
     *
     * @param array<string, mixed> $config Config options. See $_config for valid keys.
     */
    public function __construct(array $config = [])
    {
        $this->_config = $config + $this->_config;
    }
    /**
     * Checks and sets the CSRF token depending on the HTTP verb.
     *
     * @param \Psr\Http\Message\ServerRequestInterface $request The request.
     * @param \Psr\Http\Server\RequestHandlerInterface $handler The request handler.
     * @return \Psr\Http\Message\ResponseInterface A response.
     */
    public function process(Server_Request_Interface $request, Request_Handler_Interface $handler): Response_Interface
    {
        $method = $request->get_method();
        $has_data = in_array($method, ['PUT', 'POST', 'DELETE', 'PATCH'], true) || $request->get_parsed_body();
        if ($has_data && $this->skip_check_callback !== null && call_user_func($this->skip_check_callback, $request) === true) {
            $request = $this->_unset_token_field($request);
            return $handler->handle($request);
        }
        if ($request->get_attribute('csrfToken')) {
            throw new Cake_Exception('A CSRF token is already set in the request.' . "\n" . 'Ensure you do not have the CSRF middleware applied more than once. ' . 'Check both your `Application::middleware()` method and `config/routes.php`.');
        }
        $cookies = $request->get_cookie_params();
        $cookie_data = Hash::get($cookies, $this->_config['cookieName']);
        if (is_string($cookie_data) && $cookie_data !== '') {
            try {
                $request = $request->with_attribute('csrfToken', $this->salt_token($cookie_data));
            } catch (InvalidArgumentException) {
                $cookie_data = null;
            }
        }
        if ($method === 'GET' && $cookie_data === null) {
            $token = $this->create_token();
            $request = $request->with_attribute('csrfToken', $this->salt_token($token));
            $response = $handler->handle($request);
            return $this->_add_token_cookie($token, $request, $response);
        }
        if ($has_data) {
            $this->_validate_token($request);
            $request = $this->_unset_token_field($request);
        }
        return $handler->handle($request);
    }
    /**
     * Set callback for allowing to skip token check for particular request.
     *
     * The callback will receive request instance as argument and must return
     * `true` if you want to skip token check for the current request.
     *
     * @param callable $callback A callable.
     * @return $this
     */
    public function skip_check_callback(callable $callback): static
    {
        $this->skip_check_callback = $callback;
        return $this;
    }
    /**
     * Remove CSRF protection token from request data.
     *
     * @param \Psr\Http\Message\ServerRequestInterface $request The request object.
     */
    protected function _unset_token_field(Server_Request_Interface $request): Server_Request_Interface
    {
        $body = $request->get_parsed_body();
        if (is_array($body)) {
            unset($body[$this->_config['field']]);
            $request = $request->with_parsed_body($body);
        }
        return $request;
    }
    /**
     * Test if the token predates salted tokens.
     *
     * These tokens are hexadecimal values and equal
     * to the token with checksum length. While they are vulnerable
     * to BREACH they should rotate over time and support will be dropped
     * in 5.x.
     *
     * @param string $token The token to test.
     */
    protected function is_hexadecimal_token(string $token): bool
    {
        return preg_match('/^[a-f0-9]{' . static::TOKEN_WITH_CHECKSUM_LENGTH . '}$/', $token) === 1;
    }
    /**
     * Create a new token to be used for CSRF protection
     */
    public function create_token(): string
    {
        $value = Security::random_bytes(static::TOKEN_VALUE_LENGTH);
        return base64_encode($value . hash_hmac('sha1', $value, Security::get_salt()));
    }
    /**
     * Apply entropy to a CSRF token
     *
     * To avoid BREACH apply a random salt value to a token
     * When the token is compared to the session the token needs
     * to be unsalted.
     *
     * @param string $token The token to salt.
     * @return string The salted token with the salt appended.
     */
    public function salt_token(string $token): string
    {
        if ($this->is_hexadecimal_token($token)) {
            return $token;
        }
        $decoded = base64_decode($token, true);
        if ($decoded === false) {
            throw new InvalidArgumentException('Invalid token data.');
        }
        $length = strlen($decoded);
        $salt = Security::random_bytes($length);
        $salted = '';
        for ($i = 0; $i < $length; $i++) {
            // XOR the token and salt together so that we can reverse it later.
            $salted .= chr(ord($decoded[$i]) ^ ord($salt[$i]));
        }
        return base64_encode($salted . $salt);
    }
    /**
     * Remove the salt from a CSRF token.
     *
     * If the token is not TOKEN_VALUE_LENGTH * 2 it is an old
     * unsalted value that is supported for backwards compatibility.
     *
     * @param string $token The token that could be salty.
     * @return string An unsalted token.
     */
    public function unsalt_token(string $token): string
    {
        if ($this->is_hexadecimal_token($token)) {
            return $token;
        }
        $decoded = base64_decode($token, true);
        if ($decoded === false || strlen($decoded) !== static::TOKEN_WITH_CHECKSUM_LENGTH * 2) {
            return $token;
        }
        $salted = substr($decoded, 0, static::TOKEN_WITH_CHECKSUM_LENGTH);
        $salt = substr($decoded, static::TOKEN_WITH_CHECKSUM_LENGTH);
        $unsalted = '';
        for ($i = 0; $i < static::TOKEN_WITH_CHECKSUM_LENGTH; $i++) {
            // Reverse the XOR to desalt.
            $unsalted .= chr(ord($salted[$i]) ^ ord($salt[$i]));
        }
        return base64_encode($unsalted);
    }
    /**
     * Verify that CSRF token was originally generated by the receiving application.
     *
     * @param string $token The CSRF token.
     */
    protected function _verify_token(string $token): bool
    {
        // If we have a hexadecimal value we're in a compatibility mode from before
        // tokens were salted on each request.
        if ($this->is_hexadecimal_token($token)) {
            $decoded = $token;
        } else {
            $decoded = base64_decode($token, true);
        }
        if (!$decoded || strlen($decoded) <= static::TOKEN_VALUE_LENGTH) {
            return false;
        }
        $key = substr($decoded, 0, static::TOKEN_VALUE_LENGTH);
        $hmac = substr($decoded, static::TOKEN_VALUE_LENGTH);
        $expected_hmac = hash_hmac('sha1', $key, Security::get_salt());
        return hash_equals($hmac, $expected_hmac);
    }
    /**
     * Add a CSRF token to the response cookies.
     *
     * @param string $token The token to add.
     * @param \Psr\Http\Message\ServerRequestInterface $request The request to validate against.
     * @param \Psr\Http\Message\ResponseInterface $response The response.
     * @return \Psr\Http\Message\ResponseInterface $response Modified response.
     */
    protected function _add_token_cookie(string $token, Server_Request_Interface $request, Response_Interface $response): Response_Interface
    {
        $cookie = $this->_create_cookie($token, $request);
        if ($response instanceof Response) {
            return $response->with_cookie($cookie);
        }
        return $response->with_added_header('Set-Cookie', $cookie->to_header_value());
    }
    /**
     * Validate the request data against the cookie token.
     *
     * @param \Psr\Http\Message\ServerRequestInterface $request The request to validate against.
     * @throws \Cake\Http\Exception\InvalidCsrfTokenException When the CSRF token is invalid or missing.
     */
    protected function _validate_token(Server_Request_Interface $request): void
    {
        $cookie = Hash::get($request->get_cookie_params(), $this->_config['cookieName']);
        if (!$cookie || !is_string($cookie)) {
            throw new Invalid_Csrf_Token_Exception(__d('cake', 'Missing or incorrect CSRF cookie type.'));
        }
        if (!$this->_verify_token($cookie)) {
            $exception = new Invalid_Csrf_Token_Exception(__d('cake', 'Missing or invalid CSRF cookie.'));
            $expired_cookie = $this->_create_cookie('', $request)->with_expired();
            $exception->set_header('Set-Cookie', $expired_cookie->to_header_value());
            throw $exception;
        }
        $body = $request->get_parsed_body();
        if (is_array($body) || $body instanceof ArrayAccess) {
            $post = (string) Hash::get($body, $this->_config['field']);
            $post = $this->unsalt_token($post);
            if (hash_equals($post, $cookie)) {
                return;
            }
        }
        $header = $request->get_header_line('X-CSRF-Token');
        $header = $this->unsalt_token($header);
        if (hash_equals($header, $cookie)) {
            return;
        }
        throw new Invalid_Csrf_Token_Exception(__d('cake', 'CSRF token from either the request body or request headers did not match or is missing.'));
    }
    /**
     * Create response cookie
     *
     * @param string $value Cookie value
     * @param \Psr\Http\Message\ServerRequestInterface $request The request object.
     */
    protected function _create_cookie(string $value, Server_Request_Interface $request): Cookie_Interface
    {
        return Cookie::create($this->_config['cookieName'], $value, ['expires' => $this->_config['expiry'] ?: null, 'path' => $request->get_attribute('webroot'), 'secure' => $this->_config['secure'], 'httponly' => $this->_config['httponly'], 'samesite' => $this->_config['samesite']]);
    }
}